language: node_js
sudo: true
node_js:
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - node_modules
before_script:
  - npm install
script: npm test

after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'