language: node_js
sudo: true
os:
  - linux
  - osx
node_js:
  - "4"
cache:
  directories:
    - node_modules
before_script:
  - npm install
script: npm test

after_success: 
- bash <(curl -s https://codecov.io/bash)