language: node_js
sudo: true
os:
  - linux
node_js:
  - "4"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install
script: 
 - npm test
after_success: npm run coverage